---
- name: A play to play with python
  hosts: localhost

  vars:
    test_list:
      - '192.168.2.1'
      - '10.10.0.2'
      - 'host.example.org'
      - '192.168.70.0/24'
      - 'fe80::100/10'
      - True
      - 'Witcher3 The Wild Hunt'
      - 'Earl Grey Tea, hot'
    mytest_string: "ncc1701 uss enterprise"
    myaddresses: ['192.168.2.101', '10.0.3.50', '171.172.32.1']

  tasks:
  # use the jinja ipaddr filter to reveal JUST IPs from a mixed list
  - name: Just want the IPs
    debug:
      msg: "{{ test_list | ipaddr }}"

  # use the jinja randon_mac filter to finish a MAC address
  - name: spawn rando mac
    debug:
      msg: "{{'52:54:00' | random_mac }}"

  # when using the var statement Ansible would prefer you did NOT use mustache brackets
  - name: some dont req mustache brackets
    debug:
      var: "'52:54:11'|random_mac"
  # FYI - The no mustache brackets rule also applies to when statements
  # when: never use {{  }} in when statements

  # Here is an example of using a python METHOD to parse our data
  # This method returns a bool (true / false)
  - name: Test if our string ends in prise
    debug:
      msg: "{{ mytest_string.endswith('prise') }}"

  # building a conditional around our task
  # this will only print if our string ends in prise
  - name: This only prints when thistests true using python
    debug:
      msg: "Ahh but is it the Enterprise subclass A, B, C or D?"
    when: mytest_string.endswith('prise')

  # Sometimes a jinja filter seems like a lot more work to learn than just using a python method
  - name: Jinja2 way of capitalizing a string
    debug:
      msg: "{{ mytest_string | capitalize }}"

  # Same example only we use a python method not a jinja2 filter
  # notice how python methods use dot notation and jinja uses pipes
  - name: Python way of capitalizing a string
    debug:
      msg: "{{ mytest_string.capitalize() }}"

  # Sometimes we need to use python and jinja
  # ipaddr returns all the addresses that match the scope
  # the square brackets selescts the only item in the list
  # we split the IP addresses into a list containing 4 items (each item is an octet)
  # we then select the 3rd item (4th in the list) and display it to the screen
  - name: pop the number 50 on the screen
    debug:
      msg: "{{ (myaddresses|ipaddr('10.0.0.0/8'))[0].split('.')[3] }}"














